### ISSUE TITLE
oisd will continue only in abp-style (Adblock(Plus)-style domains) with 3 lists

### ISSUE THREAD

**Issue by thomasmerz** [cbuijs/oisd#1]
Hi @cbuijs , have you already seen this announcement on https://oisd.nl/downloads ?

TL;DR:
> To simplify things;
>
>oisd will continue **only in abp-style (Adblock(Plus)-style domains) with the following 3 lists**;
>
>[big.oisd.nl](https://big.oisd.nl/)
(The go-to oisd list)
[small.oisd.nl](https://small.oisd.nl/)
(if the big one is too big)
[nsfw.oisd.nl](https://nsfw.oisd.nl/)
(blocks shock/porn/adult)

Will you still be able to provide "Optimized version of OISD BlockLists"?

**Comment by durablenapkin** [comment]
Some good news - the author reverted the change to just 3 blocklists and is again offering all previously offered syntaxes: https://oisd.nl/

> The Change to one syntax was reverted.

**Comment by cbuijs** [comment]
Seems it will and has been changed again and I need to fix.

**Comment by cbuijs** [comment]
Changed to use the (further) supported `domainswild2` sources.
