### ISSUE TITLE
404 & 503

### ISSUE THREAD

**Issue by tkp206093** [cbuijs/oisd#2]
404: Not Found

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by cbuijs** [comment]
Hi @tkp206093 , I have no clue what you trying to convey. Could you ellaborate?

**Comment by tkp206093** [comment]
> Hi @tkp206093 , I have no clue what you trying to convey. Could you ellaborate?
https://raw.githubusercontent.com/sjhgvr/oisd/main/domains_small.txt
![Screenshot_20230825_123756_Samsung Internet](https://github.com/cbuijs/oisd/assets/29872453/16cbbf2c-c720-4646-9aab-155eeb1d649a)

**Comment by thomasmerz** [comment]
You took the wrong repo?
https://raw.githubusercontent.com/cbuijs/oisd/master/small/domains works fine. This is "raw" for https://github.com/cbuijs/oisd/blob/master/small/domains in THIS repo. Your link points to another repo: https://github.com/sjhgvr/oisd
